defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
source:         .
destination:    ./_site
plugins:        ./_plugins
layouts:        ./_layouts

markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
highlighter: pygments
safe: true

paginate: 8
paginate_path: "page:num"

# presonal config
title: LiLong's Blog
description: LiLong's Blog, powered by Jekyll...
feed: http://feeds2.feedburner.com/LilongsBlog

author: Li Long

seo: 
  keyword: 
  description: 
config:
  js_dir:
  img_dir:
  css_dir:
